<?php
namespace app\report\admin;
use think\Db;
use app\system\admin\Admin;
use app\report\model\Report as ReportModel;
use app\rent\model\Rent as RentModel;
include EXTEND_PATH.'phpexcel/PHPExcel.php';

class Rent extends Admin
{

    public function index()
    {
    	if ($this->request->isAjax()) {
            
        }
        return $this->fetch();
    }

    /**
     * [months 月租金报表]
     * @return [type] [description]
     */
    public function months()
    {
    	if ($this->request->isAjax()) {
            $ReportModel = new ReportModel;
            $where = [['type','eq','RentReport']];
            $getData = $this->request->post();

            $instid = (isset($getData['inst_id']) && $getData['inst_id'])?$getData['inst_id']:INST;
            $ownerid = (isset($getData['owner_id']) && $getData['owner_id'])?$getData['owner_id']:1;
            $where[] = (isset($getData['query_month']) && $getData['query_month'])?['date','eq',str_replace('-','',$getData['query_month'])]:['date','eq',date('Ym')];
            $tempData = $ReportModel->where($where)->value('data');
            if($tempData){
                $temps = json_decode($tempData,true);
                $data['data'] = isset($temps[$instid][$ownerid])?$temps[$instid][$ownerid]:[];
            }else{
                $data['data'] = [];
            }
            $temps = json_decode($tempData,true);
            $data['data'] = isset($temps[$instid][$ownerid])?$temps[$instid][$ownerid]:[];
            $data['msg'] = '';
            $data['code'] = 0;
            //halt(json_encode($data));
            return json_encode($data);
        }
        return $this->fetch();
    }

    /**
     * [months 月租金分析报表]
     * @return [type] [description]
     */
    public function analyze()
    {
    	if ($this->request->isAjax()) {

        }
        return $this->fetch();
    }

    /**
     * [months 欠租明细报表]
     * @return [type] [description]
     */
    public function unpaidRent()
    {
        if ($this->request->isAjax()) {
            $ReportModel = new ReportModel;
            $result = $ReportModel->getUnpaidRent();
            $data = [];
            $data['data'] = $result['data'];
            $data['count'] = count($result['data']);
            $data['code'] = 0;
            $data['msg'] = '';
            return json($data);
        }
        return $this->fetch();
    }

    /**
     * [months 欠租明细报表]
     * @return [type] [description]
     */
    public function export()
    {
        if ($this->request->isAjax()) {
            
            $ReportModel = new ReportModel; 
            $tableTemp =  $ReportModel->getUnpaidRent();
           
            $table = $tableTemp['data'];

            if(!$table){
                return $this->error('暂无数据导出！');
            }

            $tableData = [];
            //设置字段的排序
            $sort = ['number','address','tenant','use','curMonthUnpaidRent','beforeMonthUnpaidRent','beforeYearUnpaidRent','total','remark'];
            //标题
            $values = ['房屋编号','地址','户名','使用性质','本月欠租','以前月欠租','以前年欠租','合计欠租','备注'];
            $sortFlip = array_flip($sort);
            //将数组重新按一定顺序组装成数值型键值对数组
            $y = 0;
            foreach($table as $s){
                foreach($s as $u => $o){
                    $tableData[$y][$sortFlip[$u]] = $o;
                } 
                ksort($tableData[$y]);
                $y++;
            }
            //halt($tableData);
            $objPHPExcel = new \PHPExcel();
            $objWriter = new \PHPExcel_Writer_Excel2007($objPHPExcel); //保存excel—2007格式

            //设置文档基本属性
            $objProps = $objPHPExcel->getProperties();
            $objProps->setCreator("Lucas");
            $objProps->setLastModifiedBy("Lucas");
            $objProps->setTitle("Office XLS");
            $objProps->setSubject("Office XLS");
            $objProps->setDescription("Test document, generated by PHPExcel");
            $objProps->setKeywords("system data");
            $objProps->setCategory("data report");
            /*----------------创建sheet-----------------*/
            

            $letter = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','AA','AB','AC','AD','AE','AF','AG','AH','AI','AJ','AK','AL','AM','AN','AO','AP','AQ','AR','AS','AT','AU','AV','AW','AX','AY','AZ'];
            /*----------------创建sheet-----------------*/
            $objPHPExcel->setActiveSheetIndex(0);
            $objActSheet = $objPHPExcel->getActiveSheet();

            //设置当前活动sheet的名称
            $objActSheet->setTitle('欠租明细');


            foreach($tableData as $ak => $a){ 

                $objActSheet->getRowDimension($ak+1)->setRowHeight(16);//设置行高度

                foreach($a as $bk => $b){
    
                    if($ak === 0){ //如果是第一行
                        $objActSheet->getColumnDimension($letter[$bk])->setWidth(20); //设置列宽度                  
                        $objActSheet->getStyle($letter[$bk] . ($ak+1))->getFont()->setBold(true); //设置是否加粗
                        $objActSheet->getStyle($letter[$bk] . ($ak+1))->getFill()->setFillType(\PHPExcel_Style_Fill::FILL_SOLID);//设置填充颜色
                        $objActSheet->getStyle($letter[$bk] . ($ak+1))->getFill()->getStartColor()->setRGB('E6E6E6'); //设置填充颜色

                        $objActSheet->setCellValue($letter[$bk] . ($ak+1), ' ' . $values[$bk] . ' ');  //写入标题
                    }else{
                        $objActSheet->setCellValue($letter[$bk] . ($ak+1), ' ' . $b . ' ');
                    }
     
                }
            }
            //生成excel表格，自定义名
            $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');

            /*------------这种是保存到浏览器下载位置（客户端）-------------------*/

            $filename = $tableTemp['op'].'欠租明细_' . date('YmdHis', time()) . '.xlsx';    //定义文件名

            /*
            
            // 方案一：直接在浏览器上下载
            header("Pragma: public");
            header("Expires: 0");
            header("Cache-Control:must-revalidate, post-check=0, pre-check=0");
            header("Content-Type:application/force-download");
            header("Content-Type:application/vnd.ms-execl");
            header("Content-Type:application/octet-stream");
            header("Content-Type:application/download");
            header('Content-Disposition:attachment;filename=' . $filename);
            header("Content-Transfer-Encoding:binary");
            $objWriter->save('php://output');

            */
           
           // 方案二：先保存在服务器，然后返回文件路径
           $filePath = './upload/excel/'.convertGBK($filename); //以GBK编码保存文件到服务器，解决中文名乱码问题
           $objWriter->save($filePath);

           $returnJson = [];
           $returnJson['code'] = 1;
           $returnJson['msg'] = '导出成功！';
           $returnJson['data'] = '/upload/excel/'.$filename;
           return json($returnJson); // 返回的文件名需要是以UTF-8编码
        }
    }
}